### ISSUE TITLE
메일링 서비스 로고 깨짐 

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#104]
![2016-03-14 3 37 02](https://cloud.githubusercontent.com/assets/12493128/13736741/a7b61ade-e9fa-11e5-8c62-3f8782678c55.png)

로고 이미지 변경하면서 배경 컬러도 변경했으면 합니다. 사이즈와 위치는 모두 동일해도 될 것 같아 예시로 이미지 올려둡니다.

**Comment by mozodev** [comment]
https://github.com/parti-xyz/catan-web/commit/aceb3ef61bf7e5d68f619c0149523754b7a6df19
