### ISSUE TITLE
글자 색상/크기 변경

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#105]
![2016-03-14 4 26 59](https://cloud.githubusercontent.com/assets/12493128/13737566/9f8ab8a4-ea01-11e5-9e42-3fca01954c1e.png)
![2016-03-14 4 24 27](https://cloud.githubusercontent.com/assets/12493128/13737567/9f8d9a88-ea01-11e5-98c1-160d389fe7b7.png)
![2016-03-14 4 15 45](https://cloud.githubusercontent.com/assets/12493128/13737564/9f8a4090-ea01-11e5-9f09-0caf6ad5a995.png)
![Uploading 스크린샷 2016-03-14 오후 4.13.32.png

**Comment by berry502** [comment]
전 원래 밑줄을 선호하지는 않아서 마우스 후버 색상만 지정했는데 ... 밑줄 있었음 좋겠다고 하셔서 찾아보니. http://www.itsnicethat.com/ 이 사이트 제목에 마우스 오버하면 밑줄 붙는게 이쁘군요. 주장에도 이렇게 마우스 오버하면 밑줄 쫙쫙. 하면 예쁘려나 ..

**Comment by berry502** [comment]
<img width="779" alt="2016-03-14 9 23 45" src="https://cloud.githubusercontent.com/assets/12493128/13744441/15d0cae8-ea2b-11e5-9fb1-0c1504889429.png">

필드영역에 글씨가 회색이니 입력이 비활성화된 느낌이 들었어요. 
이슈들도 사이에 , 가 있었으면 좋겠단 생각이 들었네요

**Comment by berry502** [comment]
<img width="768" alt="2016-03-14 11 07 02" src="https://cloud.githubusercontent.com/assets/12493128/13746998/85797a4e-ea39-11e5-8230-570ba22a88eb.png">
주장 입력 필드가 좀 넓었으면 좋겠어요.

**Comment by dalikim** [comment]
아침에 제가 이야기한 게 이 스타일인데요. 쉼표로 가나요? 레이블처럼 박스를 치거나 하는건 어떤가요? @berry502

**Comment by dalikim** [comment]
글상세에 업보트를 눈에 더 띄게 보여주면 합니다.

**Comment by mozodev** [comment]
눈에 잘 보이지 않는 색상들만 수정하고 이슈는 닫겠습니다~

**Comment by mozodev** [comment]
https://github.com/parti-xyz/catan-web/commit/be8d0e5935f4bb09897e74f038754cf3fa3e9076
