### ISSUE TITLE
서머리 카드 불러오지 못하는 사이트 제보!

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/catan-web#121]
링크 제목에 url이 그대로 노출되는 애들 포함...

**Comment by mozodev** [comment]
http://www.nec.go.kr/portal/ocamain.jsp

**Comment by mozodev** [comment]
http://m.mediajeju.com/news/articleview.html?idxno=182777

**Comment by mozodev** [comment]
http://policy.nec.go.kr/svc/policy/PolicyContent02.do

**Comment by dalikim** [comment]
@mozodev 일단 올리시되, 모조님은 프로그래머니까 cafe24인지 아닌지도 정리하면서 올리시면 합니다.
