### ISSUE TITLE
링크 중복 합쳐지지 않는 현상 제보

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#128]
http://parti.xyz/articles/687 와 http://parti.xyz/articles/684 이 두개는 테스트하느라 동일 링크가 두번 걸렸는데 댓글이 합쳐지진 않네요

**Comment by dalikim** [comment]
@berry502 하나는 환경 빠띠고 다른 하나는 미니멀 한 삶 빠띠라 그렇습니다.
