### ISSUE TITLE
미팅일지 작성하기

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#137]

**Comment by dalikim** [comment]
어떤 미팅일까요? 궁금? ^^

**Comment by luluv** [comment]
@dalikim 모든 미팅에 대한 기록을 일지로 남겨보려고 합니다. 일단 제가 참여하는 미팅만이라도요.

**Comment by luluv** [comment]
외부 미팅일지에 대한 내용이 이미 와플에 있네요. 요건 삭제할게요.
