### ISSUE TITLE
퍼블리싱 엑셀

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#154]

**Comment by berry502** [comment]
완료조건 : 퍼블리싱 엑셀에 있는 qa 완료시 태스크를 닫는다.

**Comment by berry502** [comment]
https://docs.google.com/spreadsheets/d/1Biw-or_swsUbi0C_myaU3rC-6XhfgyYcRmPcokmDyHw/edit#gid=712227680

**Comment by dalikim** [comment]
완료처리할께요.
