### ISSUE TITLE
페이스북 트위터 SEO 이미지 변경

### ISSUE THREAD

**Issue by berryv** [parti-xyz/catan-web#162]
변경된 슬로건으로 바꿉니다.

**Comment by berryv** [comment]
![parti_seo](https://cloud.githubusercontent.com/assets/12493128/16038458/fdc4e628-325f-11e6-99d9-ef6e07804b17.png)

이렇게 넣는건 어때요 ? 저희같은 경우에는 자료(기사) 공유를 많이하는 편인데 브랜드 이미지가 너무 강하게 들어가니까, 클릭을 별로 하고 싶지 않더라구요. 사진 이미지로 넣고 슬로건이 작게 들어가는건 어떤지요?

**Comment by berryv** [comment]
![2016-06-14 6 47 00](https://cloud.githubusercontent.com/assets/12493128/16038555/68aa11ca-3260-11e6-81fc-da568d6df72e.png)

이렇게 나오는 부분 이미지 변경입니다. 
최초 로그인시 나오는 부분은 디벨로퍼에 들어가서 나오는 부분? 인 것 같네요. 어디에서 바꿔야하는지는 찾아보겠습니다.

**Comment by dalikim** [comment]
@berryv 개발에서 찾아서 수정할까요? https://github.com/parti-xyz/catan-web/blob/master/app/assets/images/parti_seo.png 위치는 여기입니다.

**Comment by berryv** [comment]
주신 링크에다가 동일한 파일명으로 이미지 올리고 노티드릴게요. 이 이미지와 메일 서명 슬로건엔 "함께 만드는 온라인 광장"으로 반영하겠습니다.

**Comment by berryv** [comment]
https://github.com/parti-xyz/catan-web/commit/6495f3e12be3272e1ce9dfb6ab3f7354e7c0691b 올렸습니다
