### ISSUE TITLE
온라인 툴킷 제작 1.4

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#170]
- 일반 사용자와 빠띠 메이커에게 편리하고 효율적인 빠띠 활용 가이드를 제공한다.
- 그를 통해, 사용자들의 유입을 늘인다.
https://github.com/parti-xyz/catan-web/issues/170

* 완료 조건
  * 1.4에서 릴리즈된 것을 추가
  * 다음 투킷 버전 플래닝/깃헙이슈 작성

**Comment by berry502** [comment]
1.5 라 다시 생성합니다 ;
