### ISSUE TITLE
빠띠 메인 디자인

### ISSUE THREAD

**Issue by hobread-ufo** [parti-xyz/catan-web#179]

**Comment by dalikim** [comment]
로그인 전 홈이지요?

**Comment by hobread-ufo** [comment]
네넵 로그인 전 홈이요 ^^
2016년 5월 1일 일요일, Kim youngmin<notifications@github.com>님이 작성한 메시지:

> 로그인 전 홈이지요?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/parti-xyz/catan-web/issues/179#issuecomment-216037841>
>


-- 

_________________________


*김현호 *| 호빵

Designer


Mobile : 010_9111_6075

email : hobread@ufofactory.org <summer@ufofactory.org>

_________________________

  *develops social impact*

서울특별시 중구 퇴계로 18길 77 1층

**Comment by hobread-ufo** [comment]
![type2](https://cloud.githubusercontent.com/assets/18651335/14944905/8467e29c-103d-11e6-8976-60e30d0eede1.jpg)
![type1](https://cloud.githubusercontent.com/assets/18651335/14944906/846cbf6a-103d-11e6-8600-952a1b3d02dc.jpg)

**Comment by hobread-ufo** [comment]
![_ _ 0502](https://cloud.githubusercontent.com/assets/18651335/14948207/c2d13dc2-1078-11e6-9464-96c7d4a85ff1.jpg)

**Comment by dalikim** [comment]
정말 마이너이인데요. 추천 빠띠 +/-는 개인적으로 낯설군요. 추가 같기도하고. 

슬라이드? 나 (아래로내린)>> 버튼 같은건 어떤가요?

**Comment by dalikim** [comment]
숫자에 링크 걸고 싶은데 지저분 할까요? 자꾸 마이너한 것만 보이네요 ㅎㅎ

**Comment by hobread-ufo** [comment]
숫자는 어디 숫자일까요?

**Comment by dalikim** [comment]
네 맞습니다

**Comment by hobread-ufo** [comment]
![_ _ 0502](https://cloud.githubusercontent.com/assets/18651335/14948537/689bb022-107c-11e6-86bc-3646dcb68aa3.jpg)
