### ISSUE TITLE
빠띠 개설

### ISSUE THREAD

**Issue by rest515** [parti-xyz/catan-web#183]

**Comment by rest515** [comment]
![image](https://cloud.githubusercontent.com/assets/794973/14913746/23524a96-0e40-11e6-8ad2-0b99596603b3.png)

**Comment by dalikim** [comment]
폼에 오류 보고를 기본적인 양식으로 다듬었습니다.

**Comment by hobread-ufo** [comment]
@dalikim 위에 개설 페이지, 그리고 전체빠띠에서 빠띠개설 버튼이 있으면 될런지요?  더 필요한곳 있으면 적어주세요.

**Comment by dalikim** [comment]
http://dev.parti.xyz/parties/new 링크는 여기구요.

1.3에서는 대시보드에서만 개설이 링크가 걸리면 합니다. "전체빠띠에서 빠띠개설 버튼"은 월요일 릴리즈 후에 바로 넣도록 하지요.

**Comment by hobread-ufo** [comment]
![default](https://cloud.githubusercontent.com/assets/18651335/15266764/6686a356-19ea-11e6-84fe-bfe04681179d.jpg)

**Comment by hobread-ufo** [comment]
파일위치: https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLRWhSSm02dlFjeEk
