### ISSUE TITLE
빠띠 설명 추가

### ISSUE THREAD

**Issue by rest515** [parti-xyz/catan-web#184]
개별 빠띠가 추구하는 목표를 보여줍니다.

카드 형태의 디자인과, 헤더 형태의 디자인이 필요합니다.

**Comment by rest515** [comment]
카드 형태 참고 이미지입니다.
![image](https://cloud.githubusercontent.com/assets/794973/14913813/971658dc-0e40-11e6-9897-25a6cf32941f.png)

헤더에도 들어가야 합니다.
![image](https://cloud.githubusercontent.com/assets/794973/14913819/a7f095c8-0e40-11e6-809a-2339d699e553.png)

**Comment by dalikim** [comment]
시스님의 캡쳐는 지금 실제 화면 같습니다. 1.2에 적용할 디자인 시안이 있다고 들었는데 그것과 차이가 궁금하네요.

**Comment by dalikim** [comment]
요건 통일하고 가야겠네요.
