### ISSUE TITLE
입력폼 - 빠띠 선택시에 가입하지 않은 빠띠와 빠띠 추가 항목도 보고 싶습니다

### ISSUE THREAD

**Issue by rest515** [parti-xyz/catan-web#185]
입력폼에서 빠띠 선택 콤보박스에, 가입하지 않은 빠띠와 새로운 빠띠 만들기 항목이 추가되면 좋겠습니다.

정렬은.

내가 가입한 빠띠1
내가 가입한 빠띠2
<<구분선>>
가입하지 않은 빠띠 1
가입하지 않은 빠띠 2
<<구분선>>
새로운 빠띠 만들기

가 어떨까 싶습니다.

**Comment by dalikim** [comment]
1.2에 배포될 예정입니다. https://parti-xyz.hackpad.com/--2fBBNRnnDdp @rest515

**Comment by dalikim** [comment]
가입하지 않은 빠띠 갯수가 너무 많으면 어떻게 할까요?

현재 상태에서 (구독한 빠띠와 "운영자가 추천한 빠띠"들 보여 주는 것)
새로운 빠띠 만들기와 다른 빠띠 찾기 링크만 넣는 건 어때요?
