### ISSUE TITLE
전체 빠띠에서 구독 취소할 경우 효과

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#191]

**Comment by dalikim** [comment]
@berry502 @hobread-ufo 두가지가 걸립니다.

1. 화면 이펙트에 문제
취소할 때 해당 빠띠 카드가 사라지게 되면, 그 뒤에 있는 빠띠 카드들이 주욱 따라서 움직여야 합니다. 눈이 무척 피로합니다.

<img width="782" alt="2016-05-03 12 46 04" src="https://cloud.githubusercontent.com/assets/1650024/14959142/eb82119c-10c8-11e6-85df-6091a1ed8df5.png">

2. 취소의 불편함
현재는 사용자가 한 번에 클릭으로 구독 끊기가 가능합니다. 즉 실수가 쉽다는 건데 복구가 쉽지않은 UX는 사용자에게 불친절한 UX입니다.

**Comment by dalikim** [comment]
@berry502 @hobread-ufo 의견 부탁드립니다.

**Comment by hobread-ufo** [comment]
1. 화면 이펙트 문제
원래 구독 빠띠가 적은 경우에는 괜찮을 것 같다고 생각했습니다. 간단한 모션도 되고 해서 약간의 재미가 있겠다 싶었는데, 많은 경우엔 말씀하신대로 피곤할것 같네요. — 오늘 딤드처리된 디자인으로 작업해 볼께요.

2. 취소의 불편함 
한번의 클릭으로 구독 끊기가 불가능한게 좋을까요? (예를 들면 알럿으로 물어본다든지… 이런 경우엔 복구가 쉽지 않다는건 간단히 해결될 것 같기도 합니다.)
저는 실수해서 구독 끊기를 하진 않을꺼라 생각했던거 같습니다. 영역의 구분이 안되있는 것이 아니라고 생각해서요. 그래서 복구에 대한 이슈를 크게 생각하지 못했네요. 그룹으로 삭제하는 경우엔 저도 복구에 대한 히스토리가 남아 있어도 좋겠다는 생각듭니다만, 이것도 너무 복잡한 기능이 생기는 것 같기도 해서요.   —  이 부분은 한번 논의했으면 합니다.

**Comment by dalikim** [comment]
2번에 대한 논의는 슬랙에서 계속 끌고 가보죠. 디자인 나오는데로 퍼블하겠습니다. 한 시에 나오는 디자인들이랑 같이 나오나요? 아니면 따로 나오나요? @hobread-ufo

**Comment by hobread-ufo** [comment]
지금 같이 나오게 하려고 합니다. 버튼(nomal, hover, active, disable까지요) 근데 active의 경우엔 약간 1~2픽셀정도 아래로 위치이동이 필요해서 하는게 맞는지 모르겠네요. 개인적으로 안움직여 주면 좀 이상해서...)

**Comment by hobread-ufo** [comment]
아 지금 다른 빠띠 구독하기 버튼 해 놓으신게 있으시니 거기에 맞춰서 다시 수정하겠습니다.

**Comment by hobread-ufo** [comment]
![_ 0503](https://cloud.githubusercontent.com/assets/18651335/14973977/299ca1ca-112a-11e6-809e-2bb9417baf78.jpg)

**Comment by dalikim** [comment]
좋네요. 근데, 구독하기/구독끊기 버튼 구별이 안가네요. 살짝 수정 가능할까요? @hobread-ufo 


탭은 미뤄야겠네요. 다른 깃헙 이슈로 처리하죠.

**Comment by dalikim** [comment]
@hobread-ufo 아 그리고 사이드바를 빼면 어떨까 싶은데요. 어떠세요?

**Comment by hobread-ufo** [comment]
![_ 0503](https://cloud.githubusercontent.com/assets/18651335/14974744/c4cbe8a0-1133-11e6-9423-57e3087b2431.jpg)다음 디자인 업데이트 할때는 좀더 빠띠 구독 위자드 처럼 디자인 할께요.

**Comment by dalikim** [comment]
이번 버전에 딤드처리는 없고 버튼 색만 바꾸겠습니다.
