### ISSUE TITLE
로그인 전 화면 오늘의 빠띠 모니터링

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#192]
현재는 오늘의 빠띠 - 의 인기글 중 이미지가 있는 링크 글만 보여줍니다. 더 좋은 방법을 고민해 봅니다.

**Comment by rest515** [comment]
저는 이 방식도 괜찮습니다.

**Comment by dalikim** [comment]
투표와 톡도 하일라이팅 되면 합니다.

**Comment by dalikim** [comment]
@luluv 로그인 전 화면에 껄끄러운 글이 걸리지는 않는지 매일 확인해야하는데요. 일단 매일 한 번 정도 메일로 로그인 전 화면 걸린 글을 슬랙에 올려 볼까요?

**Comment by luluv** [comment]
@dalikim 네. 필요한 작업이겠네요. 제가 매일 스탠드업 전에 올려보겠습니다~!

**Comment by dalikim** [comment]
@luluv 오늘 내일 해보고 효용이 있으면 자동화할께요 1.3 때?
