### ISSUE TITLE
개별 빠띠 각 탭의 에디터 메시지

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#193]
'서로의 입장을 명확히 밝히면 논의가 더 쉽고 재밌어집니다’ 추가여부 다시 이야기해본다.

**Comment by dalikim** [comment]
이 이슈의 명확한 의도가 파악되질 않습니다만. @berry502

**Comment by berry502** [comment]
디자인 반영될 때 나왔던 이슈입니다. 투표탭 http://parti.xyz/dashboard/opinions 에디터 버튼 메시지에 저 메시지를 추가하자는 의견이 있어 넣어둔 부분입니다.

**Comment by dalikim** [comment]
@luluv @berry502 개별빠띠 각 탭에 에디터버튼에 들어갈 문구를 정해 주세요

**Comment by dalikim** [comment]
@berry502 베리님께 어사인해 드릴께요

**Comment by luluv** [comment]
@berry502 베리님 위에 적어주신 투표탭 링크가 안열립니다. 이슈에 대한 맥락 파악이 잘 안되어서 그러는데 링크 확인 부탁드립니다.

**Comment by dalikim** [comment]
@luluv 베리님이 걸어 놓은 링크는 1.2 링크라 깨지는 거구요. 간단히 설명 드리면 개별 빠띠에 링크/톡/투표 쓰기 버튼이 걸려 있는데 레이블을 다듬어야 합니다. 룰루님 협조를 받아서 베리님이 결정해 주시면 하네요.
