### ISSUE TITLE
대시보드 - 아무것도 구독하지 않았을 경우

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#194]
—상단 메시지 2가지 타입 
   (아무것도 구독 안했을 때 : *어떤 이슈의 빠띠를 키워보시겠어요? 회원님의 관심으로 아래 빠띠를 키워 보세요.)
   (하나라도 눌렀을 때 : *구독한 이슈의 빠띠를 모아서 홈에서 볼 수 있어요. 이제 빠띠를 키워 볼까요?) 
   *부분은 강조해주세요. 
—계속하기 버튼 강조 
— ~~구독하기 / 취소하기 버튼 강조~~
— ~~구독 취소하기 버튼을 눌렀을때 딤드 처리되는 컬러 지정~~

- 정리된 이력이 궁금하시면 ufo-catan 슬랙 봐주세요 ~

**Comment by dalikim** [comment]
— ~~구독하기 / 취소하기 버튼 강조~~
— ~~구독 취소하기 버튼을 눌렀을때 딤드 처리되는 컬러 지정~~

이건 다른 태스크로 옮길께요.
