### ISSUE TITLE
"모든 빠띠" 스타일 개선

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#195]
— 지금 구독 중인 빠띠 컬럼을 삭제한다 
— http://ufofactory.org/ 의 포트폴리오 아래 탭처럼 전체 빠띠 / 구독 중인 빠띠 를 넣는다 
—빠띠 추가 버튼 삭제 (+버튼 있는 부분)

**Comment by dalikim** [comment]
마일스톤을 이번 릴리즈에서 빼겠습니다. @hobread-ufo

**Comment by hobread-ufo** [comment]
![_](https://cloud.githubusercontent.com/assets/18651335/14984185/66424bdc-117c-11e6-8732-e43fe4d47823.jpg)

**Comment by dalikim** [comment]
@hobread-ufo 구독한 빠띠가 보라 백그라운드라면, 대시보드 상단에 "구독 중 빠띠" 슬라이드의 빠띠들도 모두 보라색이어야 할까요?

**Comment by hobread-ufo** [comment]
탭으로 이동했다고 하더라도 전체보기와 비슷하면 변화에 대해 인지하지 못할 것 같았구요. 그리고 구독취소를 눌렀을때 딤드처리한거 보다는 전반적인 컬러가 변화하는게 더 나을 것 같았네요.

**Comment by dalikim** [comment]
@hobread-ufo 아. 맞네요. 

근데 제 질문은 대시보드 상단에 "구독 중 빠띠" 영역에 색깔도 "보라 백그라운드"가 되어야 하는지 였어요. 구독한 것이니까요. ( 컴포넌트의 속성 통일 )

그리고 백그라운드가 톤이 다른게 아니라 색이 다르면 구독한 것과 구독하지 않은 것이 아예 다른 무언가로 보일까 싶기도 하네요. 제안인데 구독하기/구독끊기 버튼만 다르면 어떨까요? 체크가 표시가 있던가..

**Comment by hobread-ufo** [comment]
아 그부분은 주말에 위자드 하면서 좀 해볼려구요. 보니 다른데는 다들 체크표시로 하더라구요. 플립보드도 그렇고 ^^

**Comment by hobread-ufo** [comment]
[빠띠_디자인개선 제안.pdf](https://github.com/parti-xyz/catan-web/files/251365/_.pdf)

**Comment by hobread-ufo** [comment]
빠띠 전체보기탭과 내가 구독하는 빠띠 탭의 기능을 구분하면 어떨까 합니다.
구독하기와 구독끊기는 전체보기 탭에서 내가 구독하는 빠디에서는 각 빠띠 홈으로 가는 건 어떨까요?
이렇게 생각한 건 위자드에서는 구독빠띠를 선택하면 체크만 하는 걸로 해서 구성해 보려구 하는데요. 디자인 하기전에 의견을 좀 듣고 싶네요.

**Comment by dalikim** [comment]
요건 요번 릴리즈에선 잠시 접어 둘까요? 아님 구독버튼 마무리만 하면 1.3 배포 가능할 것 같은데요.

**Comment by dalikim** [comment]
우선 이번 릴리즈에선 전체빠띠만 보는 것으로 마무리 할까 합니다 내가 구독 중인 빠띠를 모아서 볼 니즈가 없어요.

**Comment by dalikim** [comment]
@hobread-ufo 그룹을 표현하도록 변경되어야겠네요.

**Comment by dalikim** [comment]
* 빠띠 카드 스타일 : 프로필 사이드 바에 나오는 납작한 리스트 타입과 카드 타입과 최초 가입시 구독할때 카드 타입
* 그룹 배너 : v세상

**Comment by dalikim** [comment]
다른 이슈로 만들겠습니다.
