### ISSUE TITLE
빠띠의 이미지와 설명 운영

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#199]

**Comment by dalikim** [comment]
@berry502 @luluv 운영툴을 만들까요? 간단하게?

**Comment by berry502** [comment]
아! http://parti.xyz/parties/13/edit 이 부분을 사용자가 운영하는 부분 말씀이시죠

**Comment by dalikim** [comment]
@luluv 이제 룰루님 주도하시는 일이겠네요. 확인 부탁드립니다. 끝나시면 완료 처리 해주시구요.

**Comment by dalikim** [comment]
"빠띠메이커"에 "admin"이란 닉네임의 사용작가 올라가니 보기 별로네요.

http://dev.parti.xyz/p/20th-assembly

"admin"말고 다른 이름으로 바꿀까요?

@luluv

**Comment by luluv** [comment]
옙 다른 이름으로 수정하겠습니다. 
빠띠 메이커 리스트입니다. https://docs.google.com/spreadsheets/d/1mf2XG_i24ur4e1WNumHgq2yxcn-B6XHcUe6dUPjUDiY/edit#gid=2071161887

**Comment by dalikim** [comment]
@luluv 빠띠 수정 화면에 메이커 넣게 했습니다.

**Comment by luluv** [comment]
@dalikim 달리님 운영자 계정 수정하실 때 이미지 수정도 부탁드립니다. 아이디가 admain이어서 그런지 이미지만 수정하는 것도 안되네요.. 이미지는 슬랙으로 드리겠습니다.

**Comment by dalikim** [comment]
@luluv 핫픽스해야겠네요.

**Comment by dalikim** [comment]
@luluv 핫픽스 했습니다. 직접 수정 해봐주세요~ :)

**Comment by luluv** [comment]
빠띠 메이커 모두 등록되었습니다.

**Comment by luluv** [comment]
설명 등록 중입니다. 아직 닫지 말아주세요.

**Comment by dalikim** [comment]
@luluv 넵~

**Comment by dalikim** [comment]
오 드디어 끝났군요.

**Comment by luluv** [comment]
네 드디어.... ㅎㅎ
