### ISSUE TITLE
디자인 개선 제안

### ISSUE THREAD

**Issue by hobread-ufo** [parti-xyz/catan-web#201]
완료 조건
* 개선 제안서 작성
* 팀에 공유 후 피드백을 수집

**Comment by hobread-ufo** [comment]
![image](https://cloud.githubusercontent.com/assets/18651335/15004351/e80722a4-11f0-11e6-9988-bd3d4f6f90ab.png)
위에 있는 버튼 타입으로 통일 큰 버튼은 R값이8픽셀 작은 버튼들은 R값이 4필셀로 정리

**Comment by hobread-ufo** [comment]
![image](https://cloud.githubusercontent.com/assets/18651335/15004619/28a071d2-11f4-11e6-8ff9-4fa45ff3b201.png)
넷플릭스 왓챠와 같이 처음 로그인시 빠띠 구독 위자드를 만듭니다.

**Comment by hobread-ufo** [comment]
![image](https://cloud.githubusercontent.com/assets/18651335/15033454/ebfd743e-12a5-11e6-8b57-6dd193600839.png)
전체빠띠 바로가기를 별도 배너처럼 했네요. 
제가 적은 간략한 빠띠소개부분은 얘기한 다음에 추가적으로 해 보는걸로 할께요.

**Comment by dalikim** [comment]
@hobread-ufo 진행 발언인데요. 이 태스크는 완료날짜가 완료조건이면 좋겠네요. 예를 들어 다음주 화요일까지만 개선 제안할 수 있는 것을 만든다. 이런 식으로요.

**Comment by hobread-ufo** [comment]
[빠띠_디자인개선 제안.pdf](https://github.com/parti-xyz/catan-web/files/251366/_.pdf)
