### ISSUE TITLE
대시보드 스타일 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#211]

**Comment by dalikim** [comment]
무한 스크롤로 변경하겠습니다. 의견 주세요.

**Comment by dalikim** [comment]
@hobread-ufo http://dev.parti.xyz 로그인 후 대시보드 화면의 디자인을 다듬어야 합니다.

전체적으로 봐주시요. 특히 제 의견으로 꼭 봐주셨음 하는건 

* 구독 중인 빠띠
  *  빠띠 아이콘 모양의 통일
* 왼쪽 상단에 로그인 사람의 아이덴티티 영역 강조

아 그리고 톡이 표시될 때 조금 어색하네요. 톡 모달과 너무 다른 듯? 링크와 톡이 구별도 안가구요.

마지막으로 모바일 디자인도 주시면 합니다.

**Comment by dalikim** [comment]
#214 보고된 것 처럼  업보드하트 색깔도 바꿔야겠네요. @hobread-ufo 근데 업보트 숫자가 버튼 안에 들어가면 버튼 길이가 가변이 되는데요. 살짝 지저분해 질 수 있을 듯 한데요. 전 하트받은게 없을때 0 이라고 나오는 것도 그러니 숫자가 없으면 하는데...

덧붙여서요. 대시보드 바뀌면서 댓글이 연달아 두 개 나오니 멘션버튼도 너무 커 보이네요. 하트와 맨션을 비슷한 버튼으로 만들고요. 하트 (숫자) / 맨션 / 시간 요걸 한 줄로 모아 놓으면 어떨까 싶기도.

**Comment by hobread-ufo** [comment]
파일위치:https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLRWhSSm02dlFjeEk
![_](https://cloud.githubusercontent.com/assets/18651335/15263735/8891bb72-19a7-11e6-8c06-c04de9cdfb77.jpg)

**Comment by hobread-ufo** [comment]
인기글을 사이드바에 추가한다.

**Comment by hobread-ufo** [comment]
파일위치:https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLRWhSSm02dlFjeEk

**Comment by dalikim** [comment]
@hobread-ufo 시스님께 넘겨드릴께요

**Comment by dalikim** [comment]
투표에 masonry 넣었습니다.

**Comment by dalikim** [comment]
링크카드와 투표 카드에 hover 이펙트 넣었습니다. @hobread-ufo 맞는지 봐주세요. http://dev.parti.xyz

**Comment by dalikim** [comment]
@hobread-ufo 그래도 "새로운 댓글이 추가되었습니다"가 눈에 안띄는데요?

**Comment by dalikim** [comment]
남은 작업 리스트업합니다.

* 대시보드
  * 모바일
  * 쓰기 버튼과 그아래 새로 나온 댓글
  * 쓰기 폼에 검증
 
* 개별빠띠
  * 톡 hover
  * 쓰기 버튼
