### ISSUE TITLE
새로운 글이 등록되었을 경우 메시지 변경

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#212]

**Comment by berry502** [comment]
트위터의 '새로운 트윗12개 보기' 처럼 '새로운 댓글12개 보기' 로 변경되었으면 좋겠습니다. 클릭하는 느낌도 더 들도록 되었으면 좋겠네요.

**Comment by dalikim** [comment]
@hobread-ufo 어떠세요?

**Comment by hobread-ufo** [comment]
중간에 가려진 댓글인데 새로운 댓글 12개 보기가 맞는지는 모르겠습니다. ^^;;

**Comment by dalikim** [comment]
@hobread-ufo 아 중간에 가려진 댓글을 말하는게 아니라, 대시보드에서 "새로운 댓글 몇 개"를 알려주는 그 영역을 이야기하고 있습니다.
