### ISSUE TITLE
한글 닉네임

### ISSUE THREAD

**Issue by berryv** [parti-xyz/catan-web#213]
몇번 나왔던 이슈라 끌어올려 봅니다.

**Comment by dalikim** [comment]
한글 닉네임을 쓸 수 있을까요? 복잡하지만 닉네임을 "아이디"라 고쳐 부르고, 한글이 가능한 별명을 만들어 놓으면 어떨까요? @berry502

**Comment by luluv** [comment]
@dalikim 그러면 영문으로 된 아이디와 한글이 가능한 별명을 두개 다 가지게 되는 건가요? @dalikim

**Comment by dalikim** [comment]
@luluv 네, 저의 제안이 어떠세요?

**Comment by luluv** [comment]
@dalikim 사용자 입장에서 조금 헷갈릴 것 같아서 걱정되네요. 하지만, 한글 닉네임 사용에 대한 니즈가 크다면 그런식으로라도 변경하는 것이 좋을 것 같아요.

**Comment by dalikim** [comment]
@luluv @berry502 그럼 한 번 더 묵혀 두는 것은 어떨까요?

**Comment by luluv** [comment]
@dalikim 더 큰 니즈를 발견하기 전까지는 묵혀봐도 좋을 것 같습니다.

**Comment by dalikim** [comment]
또 다시 끌어 올리면, 대안으로는 사람에게 붙는 토씨 목록을 만들고 아이디 마지막에 그것이 붙지 않는 한 허용하는 겁니다.

예를 들어 "먹보님", "빗소리에게" 이런 아이디는 허용하지 않는 것이지요.
