### ISSUE TITLE
개별 빠띠 스타일 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#215]

**Comment by dalikim** [comment]
@hobread-ufo 카드에서 사용할 링크 디폴트 이미지와 링크 hover 효과를 지정해 주세요.

**Comment by dalikim** [comment]
남은 작업은

* 전체 모바일 적용
* 구독 버튼
* 빠띠 메이커
* 탭 액티브
* 개별 빠띠 홈

**Comment by dalikim** [comment]
톡 페이징

**Comment by dalikim** [comment]
@hobread-ufo :  
* 링크탭과 톡탭 쓰기 버튼 
* 링크탭에 이미지가 없는 링크 카드가 사용할 디폴트 이미지가 필요합니다. http://dev.parti.xyz/p/20th-assembly

**Comment by hobread-ufo** [comment]
![image_defalt 2x](https://cloud.githubusercontent.com/assets/18651335/15247589/3c96ff22-1950-11e6-9540-d9690cc5442c.png)이건 큰 이미지 하나만 올리면 되겠죠? 세로형은 올라간거 보고 위치 맞출 수 있으면 별도로 드리도록 할께요.

**Comment by hobread-ufo** [comment]
개별빠띠 링크, 톡, 투표 탭별 버튼 파일위치 :https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLRWhSSm02dlFjeEk
