### ISSUE TITLE
첫사용자가 로그인/회원가입 페이지에서 이메일 부분을 로그인이 아닌 이메일 가입으로 인식합니다.

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#217]
http://parti.xyz/users/sign_in 에서 다수의 사용자들이 이메일부분에 이메일을 기입하더라구요.

**Comment by dalikim** [comment]
"또는"을 "또는 이메일로 로그인" 이런 식으로 바꿔볼까요?
아니면 "==또는==" 아래 레이블을 하나 두는게 좋겠네요.

**Comment by dalikim** [comment]
간단히 디자인 가능할까요? @hobread-ufo 급한 건 아닙니다.

**Comment by hobread-ufo** [comment]
간단히 디자인 가능합니다. 급히 해도 되구요.

**Comment by hobread-ufo** [comment]
https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLa1o4RExjUGRPbTQ
