### ISSUE TITLE
행간이 너무 좁아서 읽기가 어려운것 같습니다.

### ISSUE THREAD

**Issue by hobread-ufo** [parti-xyz/catan-web#219]
![2016-05-12 10 54 42](https://cloud.githubusercontent.com/assets/18651335/15201853/2399c0c0-1830-11e6-9877-fabc29cf7137.png)
class="post__title"이란 아이인데요. line height값이 1.1이더라구요. 이거 좀더 넉넉하게 주면 어떨까 해서요.

**Comment by rest515** [comment]
css에서 line-height 표준이 현재 1.4 정도인데요. 그렇게 조정하면 될까요?

**Comment by hobread-ufo** [comment]
넵 저는 좋습니다. ^^ 감사합니다.
