### ISSUE TITLE
1.3 핫픽스

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#223]
* ~~알림 메시지 하트를 좋아요 문구로 변경~~
* ~~찬성수다/반대수다 --> 찬성/반대로 변경~~
* ~~모바일에 개별빠띠 각 탭별 쓰기 버튼~~ -->  #193
* 모바일에 개별빠띠 각 탭에서 쓰고 나면 해당 글로 가게
  --> 개별빠띠 링크 순서를 최신 댓글 붙은 순으로 변경
* ~~알림벨에 점을 더 크게~~
* ~~브라우저 크기를 축소시 메뉴 어그러지는 문제 잡기~~
* ~~빠띠소개 http://parti.xyz/about 에서 예전 화면이 쓰이고 있습니다~~ --> #233
* ~~댓글 풍선부분 UI 수정~~
* ~~프로필페이지에 프로필 이미지가 찌그러져서 보입니다.~~

**Comment by dalikim** [comment]
#225 오류가 "프로필페이지에 프로필 이미지가 찌그러져서 보입니다."와 같은 것일까요? @luluv

**Comment by luluv** [comment]
@dalikim 다릅니다. 화질에 대한 문제인데요, sns 프로필 이미지가 그대로 쓰이는데, 이미지가 너무 보기 안좋을 정도로 화질이 안좋아서요. http://parti.xyz/p/ask-parti/users

**Comment by luluv** [comment]
@dalikim 프로필 페이지에 이미지는 제대로 보이도록 수정되었는데요, 알림 종 옆에 있는 이미지는 여전히 찌그러져서 보입니다. 모바일 알림페이지에서도 마찬가지구요. 테섭에서 제대로 확인 못해서 죄송합니다.
