### ISSUE TITLE
프로필 이미지 깨지는 현상 해결

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#225]

**Comment by dalikim** [comment]
@luluv 두가지 상황이 가능한데요.

1. 소셜에서 주는 이미지가 이미 별로다
2. 우리가 이미지 프로세싱을 잘못한다.

1번이면 어쩔 수없습니다. 그죠? 1번인지 아닌지 확인하려면 예시가 하나 필요합니다. http://parti.xyz/about 여기에서 @qus1225 님 프로필 이미지 화질이 별로인데요.

@qus1225 은 어떤 경로로 등록하신 건가요?

**Comment by dalikim** [comment]
https://www.facebook.com/profile.php?id=100002013077385 쿠스님이 가입한 페이스북계정의 주소
