### ISSUE TITLE
본문 모달 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#230]

**Comment by dalikim** [comment]
특히 모바일에서 패딩이 심해서 불편합니다. 제목도 읽기 편하면 하는데 부담스럽게 커보입니다. 

본문 영역에 보라색 보더는 눈이 살짝 거슬리구요.

**Comment by hobread-ufo** [comment]
![_ 0518](https://cloud.githubusercontent.com/assets/18651335/15361256/b34e8514-1d4b-11e6-93cd-3aab82fecc34.jpg)
데스크탑 모달에서도 패딩값이 40px인데요. 20px로 변경했으면 합니다. 그리고 심플리도 업로드 했습니다. 
파일위치: https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLLTVlYmtpb25FTWs

**Comment by dalikim** [comment]
@hobread-ufo 웹에는 투표에 보더가 없는데요. http://parti.xyz/opinions/28 웹에도 넣나요? 웹도 같이 주시면 합니다.

**Comment by hobread-ufo** [comment]
아이고 잘못 넣었습니다. ㅠ,.ㅠ;;

**Comment by dalikim** [comment]
테섭에 적용한 걸 기준으로 검토 부탁드립니다. @hobread-ufo
