### ISSUE TITLE
소개 페이지

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#233]
소개 페이지를 급하게 손봐야하는데요. 이미지가 예전 것인 문제부터 수선 하면 합니다.

**Comment by berry502** [comment]
https://get.google.com/spaces/ 이 사이트 소개 부분 참고하셔도 좋을 것 같습니다 :) !

**Comment by hobread-ufo** [comment]
@berry502 아넵 저 부분은 236이슈에서 디자인 보완으로 하겠습니다. ^^ 우선 일단 이미지 교체부터 할겠습니다.

**Comment by hobread-ufo** [comment]
파일위치:https://drive.google.com/drive/u/0/folders/0BwFHw0bn5BhLa1o4RExjUGRPbTQ
파일네임:빠띠소개_0517.psd

**Comment by hobread-ufo** [comment]
![img_partiinro01 2x](https://cloud.githubusercontent.com/assets/18651335/15313745/2a9c36d4-1c48-11e6-8d2f-d6069161d66c.png)
![img_partiinro02 2x](https://cloud.githubusercontent.com/assets/18651335/15313746/2ac2314a-1c48-11e6-9b55-0ed3f114a0db.png)
![img_partiinro03 2x](https://cloud.githubusercontent.com/assets/18651335/15313747/2ad56fbc-1c48-11e6-9e2e-8e87ffe9c99d.png)
![img_partiinro04 2x](https://cloud.githubusercontent.com/assets/18651335/15313748/2ad9e966-1c48-11e6-9afc-7e4fa4fbfe8e.png)

**Comment by berry502** [comment]
#236 1.3핫픽스가 너무 많은데 236 버전으로 바로 들어가는건 어떨까요?

**Comment by dalikim** [comment]
@berry502 그럴까요?

@hobread-ufo 흠 근데 이미지가 두배 사이즈, 레티나예요?

**Comment by hobread-ufo** [comment]
레티나 사이즈 입니다.
