### ISSUE TITLE
빠띠 만들기 개선

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#234]
1) 위자드 화면에서 보여질 설명란과 개별 빠띠 홈에서 보여질 설명란을 분리하면 좋겠습니다. 
'간략한 설명'을 작성해주세요. 
'자세한 설명'을 작성해주세요. 
이런 식으로 분리하면 어떨까요?
2) 설명란에서 글자수 제한 기능이 추가되면 좋겠습니다.

**Comment by berry502** [comment]
저는 빠띠를 만드는 사람이 더 어려울 것 같아서.. 혹시 위자드 화면에서 설명을 보여주는 부분이 더 길어지면 어떨까요? 아니면 개별 빠띠 홈의 글 숫자를 좀 더 줄이거나요. 둘이 통일되면 좋겠습니다.

**Comment by luluv** [comment]
어려우려나요. 통일되면 빠띠 메이커의 번거로움을 줄여줄 수 있어서 좋을것 같은데, 현재는 위자드 55자, 개별빠띠홈 430자여서 갭이 너무 크긴 합니다. 몇자 정도가 적당할까요?

**Comment by dalikim** [comment]
일단 둘 다 만드는 것은 메이커에게 어려움을 줄 수 있을 확률이 높은데요. 메이커가 빠띠 설명을 길게 써야될 이유가 뭘까요?

**Comment by luluv** [comment]
@dalikim http://parti.xyz/p/history 빠띠 메이커분이 전달하고 싶은 내용이 길 경우가 있을 것 같은데, 지금으로써는 가이드를 드리지 않으면 위자드에서도, 개별 빠띠 홈에서도 전달력이 떨어지게 되니 생각해 본 아이디어입니다. 
둘 다 만드는 것이 메이커에게 어려움을 준다면, @berry502 님이 제안해주신 내용처럼 하나로 통일하고 글자수를 제한했으면 좋겠습니다.

**Comment by dalikim** [comment]
@luluv 네네 맞습니다. 다만 너무 길어도 읽지 않을거 같아요. 메이커야 할말이 많겠지만 한 줄로 충분히 전달되지 않는 이상 의미가 있을까 싶은데요. 대신 개별빠띠홈 + 위키에 집중하게 하는게 필요하지 않으까요?

빠띠메이커에게 호소력 짙고 매력적인 한줄의 카피와 로고를 고민케 한다.
+ 개별빠띠홈과 위키를 통해 자세한 설명을 하게 한다

요런 전략은 어떨까요?

**Comment by luluv** [comment]
@dalikim 빠띠 메이커에게 호소력 짙고 매력적인 한줄의 카페와 로고를 고민케한다. 이게 제가 바라던 것입니다! 개별  빠띠 홈에서 자세한 설명을 하게 한다면, 지금의 빠띠 홈 설명과 다른 형태를 생각하시는 거죠?

**Comment by dalikim** [comment]
@luluv 개별 빠띠 홈과 지금의 빠띠 홈(로그인 하지 않은 상태에서 http://parti.xyz 여길 말씀하시는건지요?)은 다르겠죠. 앞으로 우리가 풀어야할 숙제입니다.

**Comment by dalikim** [comment]
#183 은 닫겠습니다. 중복이네요.
