### ISSUE TITLE
에디터 개선

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#235]
https://parti-xyz.slack.com/files/berry/F19C5A9KR/slack_for_ios_upload.jpg 

링크를 넣고 의견을 적지 않았을 경우 게시버튼에 금지 아이콘으로 마우스가 변경되는데, '링크에 대한 의견을 적어주세요' 모달창 안내가 좋을 것 같습니다.

**Comment by dalikim** [comment]
에디터개선과 같이 가면 하구요.  #229 

페북/트윗 처럼 통합 에디팅으로 가지 않고 현재 텀블러 방식에 에디팅을 유지한다는 가정하에서는
빠띠 선택만 먼저 보이고 빠띠 선택 후에 아래 폼이 보여지면 어떨까 합니다.

**Comment by dalikim** [comment]
에디터를 삭제합니다.
