### ISSUE TITLE
소개페이지 개선

### ISSUE THREAD

**Issue by hobread-ufo** [parti-xyz/catan-web#236]
소개페이지 구성과 카피 및 디자인 수정

**Comment by berry502** [comment]
https://docs.google.com/presentation/d/1Nj7FqKjoZ88pdY02ndT2qlrhdXXo5rvubgexxsRod7Y/edit#slide=id.g1407db77c7_0_0 페이지 / 카피를 구성해 보았습니다.

**Comment by dalikim** [comment]
#233 과 겹치지는 않는지요?

**Comment by berry502** [comment]
#233은 이미지 변경만 우선 진행하신다네요
