### ISSUE TITLE
seo이미지가 잘못들어간 것 같습니다. 제가 확인차 캡쳐 이미지를 드렸던게 들어간 것 같아요. 저 이미지는 명함 뒷장의 가이드 선 있는 부분까지 나와있어서요. https://parti-xyz.slack.com/files/berry/F19EGMF6G/_____________2016-05-17________6.46.30.png

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#240]

**Comment by dalikim** [comment]
@berry502 seo이미지의 오류인가요? 어디가 오류인지요? URL이 필요합니다.

**Comment by berry502** [comment]
http://parti.xyz/p/climate-change 어떤 이미지인지 모르겠네요. 이건 다른 포스트인데도 이 이미지가 들어가 있어요. http://parti.xyz/articles/1392

**Comment by dalikim** [comment]
@berry502 이미지가 없을 경우 대체 이미지로 @hobread-ufo 님이 디자인 해주신 이미지 입니다. 다른 이미지로 교체할까요?

**Comment by berry502** [comment]
@hobread-ufo 한번 확인해주셔요! 제가 그때 이것 맞나요? 하면서 드린 캡쳐본이 들어간 것 같아요.

**Comment by hobread-ufo** [comment]
![image_defalt 2x](https://cloud.gith@ubusercontent.com/assets/18651335/15349711/dd007eee-1d0f-11e6-8a1b-b18833c93929.png)
@dalikim  이 이미지로 교체해 주시면 됩니다.

**Comment by hobread-ufo** [comment]
![image_defalt 2x](https://cloud.githubusercontent.com/assets/18651335/15636639/634f0544-2641-11e6-8a0f-cf10828c4b41.png)
디폴트 이미지 다시 올려 드립니다.

**Comment by berry502** [comment]
<img width="238" alt="2016-05-30 8 35 53" src="https://cloud.githubusercontent.com/assets/12493128/15636651/b3dc8afe-2641-11e6-9604-4f97fa08e337.png">

혹시 이 이미지로 해주실 수 있나요? @hobread-ufo

**Comment by hobread-ufo** [comment]
![image_defalt 2x](https://cloud.githubusercontent.com/assets/18651335/15636729/57009562-2643-11e6-96f2-f8da6d4bb630.png)

**Comment by berry502** [comment]
@dalikim 이 이미지 입니다 ~
