### ISSUE TITLE
구독하기를 참여하기 로 바꾸는 것은 어떨까요?

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#243]

**Comment by rest515** [comment]
현재 "구독하기"로 되어 있는 까닭이 빠띠에 올라오는 글을 대시보드나 메일로 보내주겠다는 의도에서 만든 문구인데요.

빠띠에 참여한다, 가입한다는 느낌을 주고 싶기는 하나. "구독하기"보다는 덜 직접적인 문구 같아요. "참여하기"나 "가입하기"는 "참여나 가입해서 어떤 일이 벌어지는지?" 잘 상상이 안 된다는 단점이 보이네요.

**Comment by qus1225** [comment]
음, 저도 처음에 빠띠서비스의 미디어적 측면을 이해하기 전까지는, 왜 구독하기라고 했는지 이해를 못했었는데요. 빠띠메이커의 컨텐츠 생산 등 미디어적 측면을 고려해보니 이유있는 네이밍이었다는 생각이들더라구요.
다만, '구독하기'는 내가 이 빠띠에 참여해서 주체적으로 이 사회문제를 해결한다는 느낌이 아니라 누군가가 올리는 컨텐츠들을 '읽기만 하는' 수동적인 느낌을 줘서. 
다른 네이밍 대안도 고민해야 하지 않을까라는 생각이드네요.

**Comment by dalikim** [comment]
구독자가 수동적인 입장을 취하기 쉬운게 현재 빠띠 모습입니다. 그게 네이밍으로만 해결되리라는데는 부정적입니다.
