### ISSUE TITLE
"캠페인" 페이지

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#246]

**Comment by dalikim** [comment]
http://dev.parti.xyz/g/parti 여기를 참조하시기 바랍니다.

**Comment by hobread-ufo** [comment]
![image](https://cloud.githubusercontent.com/assets/18651335/15532886/f0353bf2-229c-11e6-9f98-a41414344dc6.png)

**Comment by dalikim** [comment]
옷 수고 많으셨어요. 호빵님께 드리는 피드백이라기 보단 팀에 열린 질문입니다.

GNB : 센터도 좋은데 왼쪽엔 빠띠가 오른쪽엔 로그인 한 아이덴티티가 있으면 어떨까요? 그리고 바탕은 과감하게 투명하면 어떨까 싶기도 하구요. 그룹 아이덴티티를 더 강하게.

빠띠 섹션 :  빠띠 섹션엔 제목이 없어도 될까요? 헷갈릴까봐. "빠띠 (3)" 뭐 이런거?

논의 섹션 : 논의가 슬라이드 되는 이유는 뭘까요? 많이보는 글목록 테이블이면 어떨까요? (그리고 바탕색이 과하게 묵직한 듯 하네요. ㅎㅎ )
