### ISSUE TITLE
 수정창 아래 필드 삭제가 필요해 보입니다.

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#253]

**Comment by dalikim** [comment]
수정창이 많은데 어떤 건지요? 되도록 url 넣어주시면 합니다.

**Comment by berry502** [comment]
아, 모든 수정창에서 그렇습니다. 댓글이 하나만 달려 있어서 바라 아래 게시필드가 나와서 중복되어보였는데 .. 게시글이 많으면 가장 아래에 게시필드가 있으니 또 다르겠네요. 우선 두고 에디터를 바꿀 때 다른 것과 함께 이야기 되어 보면 좋겠습니다.

**Comment by dalikim** [comment]
댓글 수정창이요? 아니면 톡, 투표 수정창이요?

**Comment by berry502** [comment]
네, '댓글'입니다

**Comment by dalikim** [comment]
앞으론 URL도 주시면 커뮤니케이션이 원할하겠습니다.

**Comment by dalikim** [comment]
<img width="840" alt="2016-05-31 4 08 45" src="https://cloud.githubusercontent.com/assets/1650024/15666126/fa6ecc76-2749-11e6-9f3d-8bbbd968cbec.png">


이런 방식으로 아래는 새로 글쓰기 창이고 위에는 수정창일 경우를 표시해 준 것입니다.

보통 서비스에서 구현하는 방식인데 빠띠에서는 어색한 이유는 뭘까요? @berry502

**Comment by berry502** [comment]
넵 맞아요. 여러개 댓글이 있을때 어색하지 않았는데 댓글이 없을때 그런 기분을 크게 느꼈네요. 
저는 에디터가 화면에 가득차게 바뀌면 이 이슈가 해결되지 않을까 싶어요 . (작성/ 수정 모두)

**Comment by dalikim** [comment]
@berry502 이번 1.4개편하면서 모바일에서 댓글수정 폼을 확 키우기만 했습니다. 이정도로도 만족이 안될까요? ㅎㅎ
