### ISSUE TITLE
"홈" 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#257]
* 그룹 노출 : 광고 배너식?

**Comment by luluv** [comment]
https://docs.google.com/spreadsheets/d/1i_g_NNqmgwM0nGYU1v3-riROz58JzrAESYd8SH24hm8/edit#gid=965354417

추천빠띠 리스트

**Comment by dalikim** [comment]
@berry502 @luluv 두 분이 목록 정리되시고 이미지 만드시면 여기에 구글드라이브 링크 올려 주시고, @qus1225 님께 넘겨주세요.

**Comment by dalikim** [comment]
추천 빠띠와 인기 논의 hover가 없습니다.
투표에 hover시 맨 오른쪽 투표hover이펙트가 잘리는 현상이 있습니다.

**Comment by dalikim** [comment]
캠페인 배너를 삭제하고 위아래 마진을 잡습니다.

**Comment by dalikim** [comment]
추천 빠띠 로고 스타일 조정 : 사이즈/위치
