### ISSUE TITLE
"내 빠띠" 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#259]
* 사이드바에 참여하는 빠띠/그룹 숨기기
* 참여하는 그룹/빠띠가 3개 미만이면 참여위자드가 보입니다.

**Comment by qus1225** [comment]
@dalikim 참여하는 그룹도 3개 미만일 경우 참여위자드를 띄우는게 맞을까요? (그룹에 참여하는 것도 강제해야 되는지?)
