### ISSUE TITLE
GNB 스타일 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#260]

**Comment by dalikim** [comment]
https://app.sympli.io/app#!/designs/5746f8215397edae4369e4bf 디자인은 이 서비스를 통해서 공유합니다.

**Comment by qus1225** [comment]
리팩토링: 인라인CSS를 SCSS로 옮기기

**Comment by qus1225** [comment]
gnb언더바 적용 / 색상 수정

**Comment by qus1225** [comment]
홈화면에서는 gnb상단에 키비쥬얼(?) 띄우기

**Comment by dalikim** [comment]
프로필 보기를 추가 합니다.
