### ISSUE TITLE
대시보드 내 그룹에 소속된 빠띠 관련된 디자인

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#262]
http://dev.parti.xyz/dashboard 에서 사이드바에 구독된 빠띠나 메이커하는 빠띠를 표시하는데요.

이때 그룹소속된 빠띠는 그룹이 표시되는 다른 디자인이 필요합니다. 검토 바랍니다.

**Comment by qus1225** [comment]
<img width="285" alt="2016-05-25 5 49 54" src="https://cloud.githubusercontent.com/assets/17735106/15533973/c65215a8-22a1-11e6-8212-cc49f7e29dce.png">

요렇게 생긴 겁니다.

**Comment by dalikim** [comment]
대시보드의 노출 되는 글 중에도 그룹 소속된 빠띠에 해당되는 글은 그룹 아이덴티티가 보여야합니다.  요 디자인도 같이 해주세요. @hobread-ufo

**Comment by dalikim** [comment]
필요 없어졌습니다.
