### ISSUE TITLE
다음/네이버에 사이트 등록하기

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#263]

**Comment by dalikim** [comment]
다음과 네이버를 통한 유입을 예상해 볼까요? ㅎㅎ

**Comment by luluv** [comment]
@dalikim 넵 !

**Comment by luluv** [comment]
![2016-05-26 5 13 07](https://cloud.githubusercontent.com/assets/17918439/15568226/b2e56438-2365-11e6-9394-cbcfc7e34e63.png)

daum에는 사이트 등록을 신청했습니다. 
네이버는 대표자가 아니면, 위임장이 필요한 등 복잡한 절차가 있어서 시스님께 진행을 부탁드립니다.
아래의 웹마스터도구를 활용해서 사이트 등록/ 채널(fb, 트위터, 옐로아이디) 등록/ 페이지 수집 요청 부탁드립니다.
http://webmastertool.naver.com/

페이스북 : https://www.facebook.com/parti.xyz
트위터 : https://twitter.com/parti_xyz
옐로아이디 : @parti_xyz

@rest515

**Comment by luluv** [comment]
![2016-05-27 11 06 12](https://cloud.githubusercontent.com/assets/17918439/15595563/27983c5c-23fb-11e6-97e3-52c1cf9aad8e.png)

설명과 카테고리를 변경하여 재신청하였습니다.

**Comment by luluv** [comment]
@rest515 이곳을 확인해주시면 됩니다.

**Comment by luluv** [comment]
@rest515 진행 상황 궁급합니다.

**Comment by dalikim** [comment]
@rest515 사이트 소유html 추가했습니다. 임시로 추가했고 실배포는 다음 핫픽스에서 올라갑니다. ( @qus1225 @luluv )

**Comment by dalikim** [comment]
@rest515 완료되었나요?

**Comment by rest515** [comment]
네네. @luluv 님 최종 확인 부탁합니다.

2016. 6. 21. 오전 9:44 Kim youngmin <notifications@github.com> 작성:

**Comment by luluv** [comment]
@rest515 페이스북 페이지도 등록했으면 좋겠습니다. 
![2016-06-21 10 38 08](https://cloud.githubusercontent.com/assets/17918439/16215339/51acbbe4-379c-11e6-98e0-4fb266425e17.png)

**Comment by luluv** [comment]
@rest515 https://help.naver.com/support/contents/contents.nhn?serviceNo=14882&categoryNo=15449 여기에 나와있는 것처럼 해보시면 될 것 같습니다.

**Comment by rest515** [comment]
@luluv 페이스북, 트위터, 미디엄을 채널로 추가하였습니다.

**Comment by luluv** [comment]
@rest515 넵 수고하셨습니다! 검색에 걸릴 때까지는 며칠 걸리는 것 같은데, 최종 확인되면 댓글 남기겠습니다.

**Comment by luluv** [comment]
아직은 페북, 트위터, 미디엄은 검색에 안 나오네요. https://search.naver.com/search.naver?where=nexearch&query=%EB%B9%A0%EB%9D%A0&sm=top_hty&fbm=1&ie=utf8

**Comment by luluv** [comment]
@rest515 네이버에 검색하면 페북, 트위터, 미디엄이 안나옵니다. 확인 부탁드립니다.

**Comment by rest515** [comment]
이렇게 등록했었는데요. 다른 방법이 필요할까요?

![image](https://cloud.githubusercontent.com/assets/794973/16603484/5ffdf5a2-4357-11e6-9192-2cae6696ad3c.png)

**Comment by luluv** [comment]
찾아보니, 이렇다고 하네요. 이슈 닫겠습니다 ! 

![2016-07-06 8 59 10](https://cloud.githubusercontent.com/assets/17918439/16603585/1df9e886-4358-11e6-8d3f-bb3ed7c9f6dd.png)
