### ISSUE TITLE
새로운 알림을 확인한 후에도 빨간 점이 안 없어집니다.

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#269]

**Comment by dalikim** [comment]
없어지는데, 재현할 수 있는 방법을 알려주세요 @luluv

**Comment by luluv** [comment]
@dalikim 확인하면 없어지는데, 조금 더 있다보면 다시 빨간 점이 생겨요. 그래서 눌러보면 새로운 알림이 없구요. 저는 그게 계속 반복되어서 불편한데 재현할 수 있는 방법을 잘 모르겠네요. 저도 랜덤으로 나타나는 현상인 것 같아서요. 방법을 찾으려고 계속 지켜보고만 있네요. 조금 더 지켜보고 규칙(?)을 찾으면 말씀드릴게요.

**Comment by dalikim** [comment]
우선 닫아 놓겠습니다.
