### ISSUE TITLE
빠띠 제목 길이가 길어질 때 일부 스타일이 깨진다

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#276]

**Comment by qus1225** [comment]
<img width="152" alt="2016-06-01 8 44 38" src="https://cloud.githubusercontent.com/assets/17735106/15694019/2ec1bffc-27d5-11e6-9c20-eb51e1226411.png">

깨진다는 것이 요것처럼 빠띠 이름이 전부 안보인다는 걸 말씀하시는 걸까요?

**Comment by dalikim** [comment]
예를 들어 모바일 기기에서 글 모달을 보거나 하면 스타일이 일그러집니다.
