### ISSUE TITLE
캠페인에서 빠띠가 3개 미만일 때 중복 표시되는 빠띠가 있다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#278]

**Comment by qus1225** [comment]
@dalikim 제가 수정해봤는데, 체크부탁드립니다~

**Comment by dalikim** [comment]
커밋 소스에도 코멘트 드렸는데요.  http://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html 1개나 2개일 때는 그냥 loop 옵션을 false로 두면 어떨까요?

**Comment by qus1225** [comment]
@dalikim 수정했습니다!

**Comment by dalikim** [comment]
@qus1225 수고 많으셨는데요. 또 의견이 하나 있어요. ㅎ 고치신 것처럼 하면 해당 데이터 액션 모두 아이템 숫자에 따라 루프 여부가 동일한 로직으로 결정되는데요. 그게 맞을까요? 캠페인 뷰에서는 그게 맞지만 다른 뷰에선 아닐 수도 있는데요

**Comment by qus1225** [comment]
@dalikim 음, 이게 메인슬라이드에서도 사용된다는 것을 체크 안하고 수정했네요;; 
캠페인슬라이드에서만 해당 제한이 적용되도록 수정했습니다~

**Comment by dalikim** [comment]
data-where='campaign'보다는 data-loop=true/false가 더 낫지 않을까요? @qus1225

**Comment by qus1225** [comment]
캠페인 슬라이드에는 data-loop=false 로 설정하고,
메인 슬라이드에는 data-loop=true 로 설정하는 식을 말씀하시는건가요?

캠페인 슬라이드에서도 items가 3개이상이면 loop가 true가 되는 거라, 엄밀히말하면 항상 loop가 false는 아닌건데, 그렇게 설정하면 나중에 볼 때 헷갈리지 않을까요? @dalikim

**Comment by dalikim** [comment]
뭐가 헷갈리는건지 이해가 잘 안갑니다. 

어느 뷰인지에 따라 로직이 달라지는건 뷰에 있는게 맞지, application.js가 특정 뷰에 대한 정보까지 가지는건 가능하다면 그런 식의 디자인은 회피하는게 좋습니다.

**Comment by dalikim** [comment]
제가 오해는 부분이 있으면 말씀해 주시구요. 참고로 폐쇄의 원리(Open - Closed Principle, OCP)를 한번 공부해 보시고 토론하면 합니다
