### ISSUE TITLE
홈화면 개선

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#279]

**Comment by hobread-ufo** [comment]
@dalikim 심플리에 업로드 해 두었습니다.

**Comment by qus1225** [comment]
@dalikim 모바일 홈 작업한 것 커밋해두었습니다. 그런데, 상단배너랑 추천투표 자바스크립트쪽이 아직 구현 못한 부분이 있어서 오후에 페어할 때 여쭤보려고합니다~

**Comment by dalikim** [comment]
@berry502 http://dev.parti.xyz/ 프로토타이핑 수준으로 코딩해 놓았습니다. 설명 필요하실텐데 콜 주시면 이야기 나누고 싶습니다.

**Comment by dalikim** [comment]
@qus1225 모바일 버전은 디자인 나오면 재작업이 필요하겠습니다.

**Comment by berry502** [comment]
오늘 .. 에 등록되어 있는건 오늘 되었으면 좋겠다는 뜻인가요? ㅋㅋ

**Comment by dalikim** [comment]
@berry502 배너는 사이트 보시고 적당하게 잡아주세요. 지금 한겨레 21 대상 빠띠와 기본으로 밀던 빠띠들 정도면 어떨까 합니다. v세상 캠페인하고요.

모바일과 데탑 두개가 따로 나와야겠죠?
동적인 빠디의 카운트들(예를 들어 가입자 숫자/댓글 숫자)가 있으면 좋을지요?

**Comment by berry502** [comment]
검사로 보니 배너 사이즈 676 x 210 으로 나오네요. 확실하지는 않지만 .. 이 숫자로 해볼게요

**Comment by dalikim** [comment]
@berry502 높이는 적절히 봐주세요. 모바일도 적용되는 비율이면 좋겠네요.

**Comment by berry502** [comment]
![intro_parti_1](https://cloud.githubusercontent.com/assets/12493128/15957078/ad26fb6a-2f27-11e6-9f8f-15a102d257d6.png)

**Comment by berry502** [comment]
![Uploading intro_parti_2.png…]()

**Comment by berry502** [comment]
![intro_parti_2](https://cloud.githubusercontent.com/assets/12493128/15957279/0e18580a-2f29-11e6-8205-a99888192200.png)

**Comment by berry502** [comment]
![intro_mobile](https://cloud.githubusercontent.com/assets/12493128/15958002/c838130c-2f2d-11e6-9fa9-c503fd9b931f.png)

**Comment by berry502** [comment]
![intro_mobile_2](https://cloud.githubusercontent.com/assets/12493128/15958201/16114336-2f2f-11e6-8f89-9724acef2f76.png)

**Comment by dalikim** [comment]
다시 생성하는게 좋겠습니다. @berry502 이유는 1. 이 이슈의 목적을 이미 다 달성 했고 2. 하나의 이슈가 오래 끌리는게 좋지 않거든요.
