### ISSUE TITLE
소개 페이지 리뉴얼

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#281]

**Comment by hobread-ufo** [comment]
심플리 업로드 했습니다. 
이미지도 같이 업로드 합니다.
[이미지.zip](https://github.com/parti-xyz/catan-web/files/300626/default.zip)

**Comment by dalikim** [comment]
@qus1225 소개 페이지 남은 일을 기입해 주시면 합니다.

**Comment by qus1225** [comment]
폰트와 이미지 사이즈를 em에서 px로 바꿔봤는데도, 모바일에서 깨지는 것을 막지를 못하겠네요..;;
@dalikim

**Comment by dalikim** [comment]
@qus1225 로그인 한 사람이 볼때 "가입 버튼"등을 숨기고 여러 버튼 다른 처리를 해야겠어요
