### ISSUE TITLE
알림 페이지에서 프로필 이미지 찌그러짐 현상 해결해주세요.

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#284]

**Comment by luluv** [comment]
![2016-06-07 8 39 13](https://cloud.githubusercontent.com/assets/17918439/15841351/9d2d0ef0-2c8b-11e6-8f30-ed1599da2bdb.png)

**Comment by luluv** [comment]
![2016-06-07 11 13 59](https://cloud.githubusercontent.com/assets/17918439/15843932/03383e9e-2ca1-11e6-8b00-f1d4f81a0311.png)
이렇게 보여집니다. @qus1225

**Comment by luluv** [comment]
@dalikim @qus1225 여전히 위에 등록한 사진처럼 보입니다.

**Comment by qus1225** [comment]
넵 수정하겠습니다!

**Comment by dalikim** [comment]
@luluv 혹시 해결된 건 아닌지요?

**Comment by luluv** [comment]
@dalikim 다시확인해봤는데요, 이상하게 저 pizza님 사진만 그대로 보여요...
