### ISSUE TITLE
개별 빠띠 운영 가이드 v0.2

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#289]

**Comment by dalikim** [comment]
목표 잡아주시면 팔로업 하기 편하겠습니다. 부탁드립니다.

**Comment by luluv** [comment]
https://docs.google.com/document/d/1GYkcCZf2H6xWXFgX3mpgVAfS8BxybXzlVU1Ta4ki8lk/edit
개별 빠띠 운영가이드의 목적/목표는 위 진행중문서에서 보실 수 있습니다.
v0.2의 목표- 논의/자료/투표 세부 내용 작성
