### ISSUE TITLE
모바일 사이드 메뉴에 옐로 아이디 추가하기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#294]
http://dev.parti.xyz에 추가했는데요 카톡이라는 느낌이 팍팍오게 아이콘이 수정되면 합니다

**Comment by dalikim** [comment]
<img width="257" alt="2016-06-13 9 28 38" src="https://cloud.githubusercontent.com/assets/1650024/15994807/5cc40c7a-3149-11e6-87e2-3b54c52c1cd4.png">

**Comment by berry502** [comment]
클릭하면 링크로 바로 가니까 카톡 아이콘으로 만들게욥

**Comment by berry502** [comment]
모바일 
<img width="357" alt="2016-06-13 11 50 38" src="https://cloud.githubusercontent.com/assets/12493128/15995947/38a49d46-315d-11e6-9986-756f7f7930b7.png">

![yellowid_mobile](https://cloud.githubusercontent.com/assets/12493128/15995952/44db1da6-315d-11e6-919c-998e1177bf5d.png)


웹도 바꾸는 건 어떨까 해서 넣어요 

![yellowid_web](https://cloud.githubusercontent.com/assets/12493128/15995957/4d4e9c7e-315d-11e6-9110-33be3eddcff9.png)

지금 소셜미디어 아이콘있는 자리에 4개 들어가면 좋을 것 같아요.

**Comment by dalikim** [comment]
웹에선 숨기곤 있습니다. 카톡이 데탑에서도 되긴하는데 이 링크가 데탑에서 안되는걸로 알아서요 

근데 라이센스랑 한줄에 같이 들어가니까 좀 그러네요. @parti-xyz katalk 하고 줄바꿈하고 라이센스면 어떨까요?

@berry502

**Comment by berry502** [comment]
<img width="195" alt="2016-06-13 1 04 00" src="https://cloud.githubusercontent.com/assets/12493128/15996886/f69cdaa2-3167-11e6-9c5c-9d8f04671b2a.png">

![kakaoid_mobile](https://cloud.githubusercontent.com/assets/12493128/15996888/fa84a884-3167-11e6-83d3-44448907b0aa.png)
@dalikim 이렇게 넣어봤어요.
