### ISSUE TITLE
빠띠 카드 퍼블 오류

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#299]
빠띠 설명이 길 경우, 카드를 넘어가 버림.
빠띠 설명으로 뿌려주는 텍스트 수 제한을 넣어줘야할 듯 합니다.

**Comment by qus1225** [comment]
<img width="746" alt="2016-06-13 8 23 08" src="https://cloud.githubusercontent.com/assets/17735106/15994479/affc4e38-3140-11e6-842a-21c6e11f6318.png">
<img width="563" alt="2016-06-13 8 25 14" src="https://cloud.githubusercontent.com/assets/17735106/15994480/affcf446-3140-11e6-983e-0f39ea3b96ec.png">

**Comment by dalikim** [comment]
해당 URL을 주실 수 있나요?
