### ISSUE TITLE
홈 배너 - 빠띠용

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#300]
parti-xyz/parti-group#140 에서 옮겨 옵니다. 룰루님 핸드스케치 부탁드립니다.

**Comment by luluv** [comment]
![slack for ios upload-11](https://cloud.githubusercontent.com/assets/17918439/15998897/c35725a2-317c-11e6-9395-e1c79585c125.jpg)

@dalikim 브런치를 참고해서 그려보았습니다. https://brunch.co.kr/

**Comment by dalikim** [comment]
@berryv 이 안으로 디자인 가능할까요?

**Comment by dalikim** [comment]
@luluv 운영툴을 만들면 어떨까요?

**Comment by luluv** [comment]
@dalikim 좋습니다. 글 제목과 사진 등도 변경할 수 있도록 되면 좋겠습니다 !

**Comment by berryv** [comment]
![keyvisual_1](https://cloud.githubusercontent.com/assets/12493128/16033722/95983c92-3248-11e6-80a3-649c8e984077.png)
![keyvisual_2](https://cloud.githubusercontent.com/assets/12493128/16033725/9846bab8-3248-11e6-8bfc-b55463a566fe.png)
![keyvisual_3](https://cloud.githubusercontent.com/assets/12493128/16033727/9a3d43b4-3248-11e6-88f1-44cdcca3e922.png)

영역이 작아서 그리드를 많이 못넣고 반반씩했어요. (글자가 나중에 다 나올듯;)
피드백 받고 다시 들어갈게요. @luluv @dalikim

**Comment by luluv** [comment]
오. 디자인 예뻐요! 그런데 반반으로만 가능한 것인가요? 마지막 이미지처럼 오늘의 빠띠와 관련 논의/자료/투표를 보여줘야하는 경우에는 자료/투표도 클릭하면 보여지는 기능이 있는 걸 생각하신거죠?

**Comment by berryv** [comment]
@luluv 네, 논의, 자료, 투표 하나씩 선택해서 나오는 걸로 생각했어요. 말씀하신대로 필요없는 정보는 다 빼고요. 들어가는게 별로 없으니 좋긴 하네요 ㅋㅋ

**Comment by luluv** [comment]
네. 정보가 많지 않으니 오히려 눈에도 쏙 들어오고 궁금증이 생겨요(저만 그럴지도...?) 글 제목을 잘 정해야겠네요 !

**Comment by dalikim** [comment]
@berryv 캠페인은 오른쪽에 뭐가 나오나요? 뭔가 컨텐츠가 있어야할 공간인데 덜 채워진걸로 보이네요.

**Comment by berryv** [comment]
@dalikim 캠페인은 풀 이미지로 넣고 글자영역에만 검은색 바탕을 두었습니다. 검은 색 바탕 제거한 스타일도 한번 올려볼게요

**Comment by dalikim** [comment]
@luluv http://dev.parti.xyz/admin 운영툴 간단히 만들었습니다. 관리자 권한만 접근가능하구요. 간단한 설명 필요하시면 call 해주세요.

**Comment by dalikim** [comment]
@berryv 네 그렇게 하니까 밝은 영역에 뭔가 텅 빈느낌이 들어서 어색한데. 괜찮으면 그냥 가구요.

**Comment by berryv** [comment]
psd 전달. 캠페인 스타일 1 이란 레이어도 넣어뒀습니다. 저는 처음에드린 디자인이 이쁘긴한데 달리님 말씀에는 동이에요. 지금 사진이 그래서 더 그럴 수도있고요. 

논의 / 투표에는 제목아래 발제자 아이디가 들어가는데, 자료에는 아이디 없이 들어가면 될 것 같습니다. 룰루님 요청으로는 이미지 설정, 제목 설정 모두 관리툴로 운영되면 좋겠다고 하셨어요.

**Comment by dalikim** [comment]
@berryv 실제 배포할 대기가 되면 "배포 대기"칸으로 옮기면 어떨까요? 예를 들면 테스트서버 배포라든가.

**Comment by berryv** [comment]
넵

**Comment by dalikim** [comment]
@berryv mobile디자인 해주세요 http://parti.dev/ 그리고 캠페인배너는 통 이미지로 넣게 해봤습니다. 의견 주시구요 ( @berryv  @luluv @qus1225  )

**Comment by luluv** [comment]
@dalikim url주소가 http://dev.parti.xyz/ 인가요?

**Comment by dalikim** [comment]
@luluv 수정보았습니다. 검토해 주세요

**Comment by berryv** [comment]
![keyvisual_mobile_1](https://cloud.githubusercontent.com/assets/12493128/16141793/3029ed84-349a-11e6-9139-cfa258457a4f.png)
캠페인 입니다. 

![keyvisual_mobile_2](https://cloud.githubusercontent.com/assets/12493128/16141799/3ab2fa20-349a-11e6-8447-284f620d7725.png)
오늘의 빠띠입니다. 

피드백 주세요~

**Comment by luluv** [comment]
좋습니다~ 그런데 '오늘의 빠띠'라는 이름이 걸려요. 빠띠를 매일 다르게 운영하기는 힘들 것 같아서요. '이 주의 빠띠' 정도로 바꾸면 어떨까 싶습니다.

**Comment by berryv** [comment]
![keyvisual_2_1](https://cloud.githubusercontent.com/assets/12493128/16172675/28610ea0-35c8-11e6-9916-30ca977f1064.png)
![keyvisual_2_2](https://cloud.githubusercontent.com/assets/12493128/16172677/2b34ee1c-35c8-11e6-9872-4cd4efb99b86.png)

뭐가 높다고 하셔서 바꿔봤어요.(아마 제가 완전히 이해를 못한듯 한데) 지금 빠띠에 이쁘게 반영하셨네요.. 제가 발디자인이라 고생하시는 .. ; '이 주의 빠띠'로 바꾸었네요.

**Comment by luluv** [comment]
@dalikim 이미지 사이즈 공유 부탁드립니다. '이 주의 빠띠' 웹용/ 모바일용, '캠페인' 웹용/모바일용 총 4가지 모두 부탁드려요.

**Comment by luluv** [comment]
@dalikim 달리님~ 오늘의 빠띠 -> 이주의 빠띠로 변경해주세요.

**Comment by dalikim** [comment]
@luluv 네. 근데 굳이 ㅎㅎ
