### ISSUE TITLE
페이스북 트위터를 통한 최초 로그인 할 때 나오는 빠띠 이미지 변경

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#305]
이미지 부탁드립니다. @berry502

**Comment by berryv** [comment]
파비콘이랑 로고를 다시 한번만 점검 하고 싶어서 내일까지 할게요

**Comment by berryv** [comment]
#110 이랑 동일한 것 맞나요? 
페북 : https://developers.facebook.com/apps/743728572394700/app-details/
트위터는 어디서 바꿔야할지 모르겠네요. 찾아볼게요.ㅜ ㅜ 

추가사항 - 
트위터 미디어 상단 이미지 
미디엄 로고

**Comment by dalikim** [comment]
#110 이랑은 다른건데요?

**Comment by berryv** [comment]
혹시 뭔지 알려주실래요? 어떤걸 해야하는지 모르겠어요.

**Comment by dalikim** [comment]
트위터 : https://apps.twitter.com/app/12000416/settings
