### ISSUE TITLE
개별빠띠 활용가이드 v1.3

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#311]

**Comment by dalikim** [comment]
위키 관련 부분을 넣어 주세요. 그리고 이번 주 변경되는 부분에 대해 협의 한 번 했으면 합니다. @luluv

**Comment by dalikim** [comment]
@luluv 그리고 운영가이드라고 되어 있는 이슈 제목을 "활용가이드"로 바꾸면 어떨까요?

**Comment by luluv** [comment]
@dalikim 네 위키를 제가 먼저 써보고 넣으려고 합니다. 변경되는 부분은 일단 위키 부분인데, 내일 중으로 세션을 열어야겠네요.

**Comment by luluv** [comment]
https://github.com/parti-xyz/catan-web/wiki/%EB%B9%A0%EB%9D%A0-%ED%99%9C%EC%9A%A9-%EA%B0%80%EC%9D%B4%EB%93%9C
한줄가이드 및 위키 부분 추가했습니다

**Comment by dalikim** [comment]
잘 읽어 보았습니다. 

위키에 대해 목록으로 간략히 정리되어 있는데요.

위키에 대한 간략한 설명과 위키를 처음 보는 사람들이 가지는 궁금증에 대해 답해주는 식이면 어떨까 아이디어 더해 봅니다.

-------------------------

위키는 문서 편집이 모든 사람에게 열려 있습니다. 누구나 지식을 기여할 수 있고 잘못된 정보나 문서 훼손은 이용자 스스로가 고쳐나가.... 블라블라

Q. 남이 적은 글을 고쳐도 되나요?
A. 네!  어쩌고저쩌고

Q. 혹시 잘못 고치면 어쩌나요?
A. 블라블라.

Q...
A..


------------------------

과한가 싶긴 하지만 아이디어 차원에서 드려 봅니다.

**Comment by luluv** [comment]
막막했는데, 좋은 아이디어같아요. 시도해보겠습니다ㅎㅎ

**Comment by luluv** [comment]
https://github.com/parti-xyz/catan-web/wiki/%EB%B9%A0%EB%9D%A0-%ED%99%9C%EC%9A%A9-%EA%B0%80%EC%9D%B4%EB%93%9C
위키 부분 수정해서 넣어봤습니다.
