### ISSUE TITLE
카카오/트위터 API앱 등록

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#32]

**Comment by mozodev** [comment]
![로그인 버튼](https://developers.kakao.com/assets/img/about/logos/login/kr/kakao_account_login_btn_medium_wide_ov.png)

**Comment by mozodev** [comment]
트위터로 가입 시도 시 이메일 없어서 못 넘어감...
```
이메일 값을 입력해 주세요
이메일 translation missing: ko.activerecord.errors.models.user.attributes.email.invalid
```

**Comment by dalikim** [comment]
네 트윗은 코딩을 못했죠. 제가 앱등록이 안되어서 ㅎ
