### ISSUE TITLE
담벼락 노트 삭제 관련 예외처리

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#327]
삭제할 때 노트가 없는 경우가 있습니다. 예를 들어 브라우저를 끄지 않고 놔둔채로 있다가 다른 탭 열어서 삭제한 뒤에 모르고 또 같은 노트를 삭제 할 수 있습니다. 이 경우를 처리해 주면 합니다

**Comment by qus1225** [comment]
이미 삭제 한 노트를 삭제하는 경우,
해당 id의 노트를 찾을 수없다는 ActiveRecord::RecordNotFound 에러가 떠서,

**Comment by dalikim** [comment]
@qus1225 Rails.env.development 인 경우는 404.html화면으로 일부러 가지 않게 하여 개발의 편의를 도모하였었는데 불편하셨는지요? 저는 이미 삭제 한 노트를 삭제하는 경우는 ActiveRecord::RecordNotFound가 일어나지 않게 처리하면 합니다.
