### ISSUE TITLE
전체 담벼락의 개별 노트에 빠띠가 표시되는지 확인

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#328]

**Comment by qus1225** [comment]
@dalikim 
![2016-06-24 2 08 05](https://cloud.githubusercontent.com/assets/17735106/16328436/20d30354-3a15-11e6-98c6-0ac2debcde6b.png)
위에 것처럼 전체 담벼락에서 노트 클릭했을때 나오는 모달화면에서 빠띠가 나오면 되는건가요?

**Comment by dalikim** [comment]
@qus1225 목록에서도 나와야죠. 나오고 있나 확인 해주세요.

**Comment by qus1225** [comment]
@dalikim 확인해주세요~

**Comment by dalikim** [comment]
빠띠로고는 네모로 표시하고 있습니다.

**Comment by qus1225** [comment]
@dalikim 수정했습니다!
