### ISSUE TITLE
개별 빠띠 홈 만들기

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#332]

**Comment by dalikim** [comment]
1.8로 돌릴께요.

**Comment by qus1225** [comment]
새로운 수다 개수에, 전체 수다 개수가 나옴

**Comment by qus1225** [comment]
개별빠띠 홈화면에 나오는 게시물들이 어디(논의,담벼락 등)에 해당되는지 표시

**Comment by qus1225** [comment]
<시간기록>
- 30분
  -[완료] 개별빠띠 홈화면에 나오는 게시물들이 어디(논의,담벼락 등)에 해당되는지 표시
  -[완료] 관련 빠띠 없으면 안 나오게, 우측에 푸터 붙이기
