### ISSUE TITLE
개별 빠띠 헤더 개선

### ISSUE THREAD

**Issue by rest515** [parti-xyz/catan-web#337]
개별 빠띠 헤더의 크기를 많이 줄여 봅니다. 빠띠 메뉴의 크기도 줄입니다.

**Comment by qus1225** [comment]
- 개별 빠띠 헤더 크기 줄이기

**Comment by qus1225** [comment]
<시간기록>
- 30분
  - 한것
    - 개별빠띠 메뉴 백그라운드 컬러 통일 #2a164b, 폰트에 쉐도우효과 주기
    - (issue.scss  에 .parti-header-section 설정이 2개여서 스타일 먹이는데 시간이 좀 걸림)
  - 진행중
    - 백그라운드 이미지 위에 black overlay주는방법을 찾는 중이다. div를 겹치는 방법말고 'linear-gradients' 속성을 주는 방법이 있는데, 이게 ie10부터 호환이 된다하여 하위버전에서 호환이 되는 방법을 찾는 중이다.

**Comment by dalikim** [comment]
div를 겹치지 않고 보통은 :after를 합니다 @qus1225
