### ISSUE TITLE
홈화면에 빠띠 순서 조정

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#338]

**Comment by rest515** [comment]
빠띠 이름 앞에 "공백"이 들어가 있으면 제일 처음 나오네요. 우선 급하게 빠띠 이름에서 공백을 제거하였습니다.

**Comment by qus1225** [comment]
- 전체 홈화면 순서에 이름순, 인기순 버튼 넣기

**Comment by qus1225** [comment]
<시간기록>
- 30분
  - [진행] 전체 홈화면 순서에 이름순, 인기순, 최신순 버튼 넣기

**Comment by qus1225** [comment]
- 메인 슬라이드 height 고정
- sorting, a링크에 return false를 주던지, a말고 다른걸 쓰던지 해야함
