### ISSUE TITLE
레이블 통일하기

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#345]
- 참여 -> 구독으로 레이블 변경
  - about페이지는 구독으로 하면 어색한것 같아 보류 중입니다
  - ~~about 페이지를 제외한 나머지 레이블 변경~~
- 구독회원 or 구독중인 회원 결정
  - 구독회원으로 변경

**Comment by qus1225** [comment]
음 .. 그런데 참여를 전부 구독으로 바꾸다 보니 좀 어색한 것같기도 한데요. 일단 바꾸겠습니다.

**Comment by dalikim** [comment]
어느 부분이 어색할까요? 같이 논의해 보면 합니다.
