### ISSUE TITLE
빠띠 만들기 페이지에서 대표 이미지 픽셀 가이드 추가해주세요.

### ISSUE THREAD

**Issue by luluv** [parti-xyz/catan-web#352]
http://parti.xyz/parties/new

**Comment by qus1225** [comment]
@dalikim 빠띠대표 이미지가 쓰이는 곳 중 가장 큰 사이즈로 쓰는 곳을 찾아보니, '메인의 모든 빠띠에서 나오는 빠띠리스트'의 이미지인데요 이게 가로 200px, 세로 200px인데, 이 사이즈로 가이드를 주면 될까요?
