### ISSUE TITLE
개별 빠띠 헤더 개선

### ISSUE THREAD

**Issue by qus1225** [parti-xyz/catan-web#357]
<상세 태스크>
- 개별빠띠 커버를 지우고 로고만 관리하게 합니다?
- ~~백그라운드 패턴이미지 사이즈를 확인~~
- ~~빠띠 백그라운드 블러 약하게 해봅니다~~
- ~~모바일에서 개별빠띠 상단에 패턴이 간헐적으로 표시되지 않는 버그를 수정합니다~~

**Comment by dalikim** [comment]
모바일에서 개별빠띠 상단에 패턴이 간헐적으로 표시되지 않는 버그를 수정합니다

**Comment by qus1225** [comment]
@dalikim '개별빠띠 커버를 지우고 로고만 관리하게 합니다?' 이 부분 하기로 결정된건가요?

**Comment by dalikim** [comment]
@qus1225 네. 이견 있으세요?

**Comment by qus1225** [comment]
@dalikim 없습니다!
