### ISSUE TITLE
기존 위키 데이터를 마크다운으로 마이그레이션

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/catan-web#373]

**Comment by luluv** [comment]
@dalikim 어떤 빠띠인지 알려주세요

**Comment by luluv** [comment]
"기본소득 받고 싶당"
"환경”
"일본군 위안부”
"성매매도 노동이당”
"재활용 해야한당”
"일과 삶은 하나당”
"GMO, 나는 알아야겠당" 
"미국 대통령선거 진짜 중요하당" 
"전자파 걱정된당"
"세상을 바꾸려고 대학부터 바꾼당"
"금남로 정치페스티벌"

데이터 마이그레이션 완료했습니다 !
