### ISSUE TITLE
페이스북 위젯 달기

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/catan-web#61]
http://en.vonvon.me/
처음 들어오자마자 다짜고짜 페이스북 페이지 좋아요 위젯 전체 라이트박스로!
하단에 페북 페이지 위젯.

http://kr.vonvon.me/quiz/958
로그인하고 시작하기

http://kr.vonvon.me/quiz/954

**Comment by dalikim** [comment]
좀더 보고 진행했으면 합니다. 일단 닫아볼께요. 이견 받습니다.
