### ISSUE TITLE
이슈별 post 목록 화면 구현

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/catan-web#7]

**Comment by dalikim** [comment]
이슈별 post 순서는 최근에 투표가 되거나 댓글이 달리거나 하는 순

**Comment by dalikim** [comment]
하트와 투표숫자가 올라가면 post가 상단으로 배치되는건 일단 뺐습니다. 

하트나 투표 숫자가 하나 증가할 때가 아니라
100단위로 증가할 때마다라든가 특정 문턱값들을 돌파 할때마다 
상단으로 배치하는 건 어떨까 싶어지는데요.
