### ISSUE TITLE
메인터넌스 페이지 개선

### ISSUE THREAD

**Issue by rest515** [parti-xyz/catan-web#73]

**Comment by dalikim** [comment]
모바일에서 화면이 넘칩니다.

**Comment by berry502** [comment]
maintenance.png업로드 
로딩은 이미지는 여기서 css다운로드 가능합니다. http://goo.gl/ea205h

**Comment by berry502** [comment]
parti_logo_grey.png 로 올려주세요

**Comment by berry502** [comment]
http://goo.gl/idDb7N 로딩이미지 컬러 변경했습니다.

**Comment by mozodev** [comment]
https://github.com/parti-xyz/catan-web/commit/82557e91500e06b31200c23dce3199a9d3af5feb
