### ISSUE TITLE
로그인 버튼 색상, 로그인 스타일 맞추기 

### ISSUE THREAD

**Issue by berry502** [parti-xyz/catan-web#88]

**Comment by berry502** [comment]
메뉴 '페이스북 아이디로 빠띠 계속하기' 
버튼들을 화이트 글씨에 고스트버튼 스타일로 할 수 있을까요? 찾아보니 이런것두.. http://sixrevisions.com/css/ghost-buttons/

**Comment by berry502** [comment]
햄버거 버튼에 추가될 '페이스북으로 시작하기' '구글플러스로 시작하기'는 바로 해당 부분으로 연결되고, '이메일로 시작하기' 는 현재 http://parti.xyz/users/sign_in 이 페이지로

**Comment by berry502** [comment]
로그인 모달 스타일 통일하셨다고 하여 이슈닫음.

**Comment by dalikim** [comment]
다시 열면 자동 어사인이 되네요. 헛

버튼 모양 및 색상과 모달바탕 색상 등은 다시 잡아야합니다.

**Comment by berry502** [comment]
<img width="668" alt="2016-03-14 3 22 44" src="https://cloud.githubusercontent.com/assets/12493128/13736549/c2884000-e9f8-11e5-9269-67c35f39ef6c.png">

배경 딤드 투명도는 현재와 동일하게, 색상은 #fafafb, 
버튼 색상도 바꿀 수 있다면 프라이머리 컬러 #966fdb 로 바꾸었으면 합니다.
